language: java
    jdk: oraclejdk8

    sudo: false # faster builds

    cache:
      directories:
        - '$HOME/.m2'

    script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      mvn test -B