language: java
jdk: openjdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
install:
  apt install -y protobuf-compiler
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B